# Generated by Django 2.0.1 on 2018-10-28 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FakeDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('speciality', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('hospital', models.CharField(max_length=200)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.County')),
            ],
        ),
    ]
